#!/applications/R/R-3.5.0/bin/Rscript

# Plot ChIP and input enrichment fingerprints (Lorenz curves) generated by deepTools

library(dplyr)

REC8tab <- read.table("./REC8_ChIP_input_fingerprints.tab",
                    header = T)
SPO11tab <- read.table("/projects/ajt200/BAM_masters/SPO11_ChIP/WT/SPO11_1_fingerprints.tab",
                       header = T)
H3tab <- read.table("/home/ajt200/analysis/170920_Chris_ChIP_REC8_histone/fastq_pooled/histone_ChIP_fingerprints/histone_ChIP_input_fingerprints.tab",
                    header = T)

# REC8
wt_REC8_MYC_Rep1_ChIP <- REC8tab$wt_REC8_MYC_Rep1_ChIP[order(REC8tab$wt_REC8_MYC_Rep1_ChIP,
                                                             decreasing = F)]
wt_REC8_HA_Rep2_ChIP <- REC8tab$wt_REC8_HA_Rep2_ChIP[order(REC8tab$wt_REC8_HA_Rep2_ChIP,
                                                           decreasing = F)]
kss_REC8_HA_Rep1_ChIP <- REC8tab$kss_REC8_HA_Rep1_ChIP[order(REC8tab$kss_REC8_HA_Rep1_ChIP,
                                                             decreasing = F)]
wt_REC8_MYC_Rep1_input <- REC8tab$wt_REC8_MYC_Rep1_input[order(REC8tab$wt_REC8_MYC_Rep1_input,
                                                               decreasing = F)]
kss_REC8_HA_Rep1_input <- REC8tab$kss_REC8_HA_Rep1_input[order(REC8tab$kss_REC8_HA_Rep1_input,
                                                               decreasing = F)]

REC8list <- list(wt_REC8_MYC_Rep1_ChIP,
                 wt_REC8_HA_Rep2_ChIP,
                 kss_REC8_HA_Rep1_ChIP,
                 wt_REC8_MYC_Rep1_input,
                 kss_REC8_HA_Rep1_input)

REC8names <- c("wt REC8-Myc ChIP",
               "wt REC8-HA ChIP",
               "kss REC8-HA ChIP",
               "wt REC8 input",
               "kss REC8 input")

REC8colours <- c("goldenrod1", "red", "red4", "lightblue", "lightblue4", "black")
 
# SPO11-1-oligos
SPO11_1_oligos_Rep1 <- SPO11tab$SPO11_1_oligos_Rep1[order(SPO11tab$SPO11_1_oligos_Rep1,
                                                          decreasing = F)]
SPO11_1_oligos_Rep2 <- SPO11tab$SPO11_1_oligos_Rep2[order(SPO11tab$SPO11_1_oligos_Rep2,
                                                          decreasing = F)]
SPO11_1_oligos_Rep3 <- SPO11tab$SPO11_1_oligos_Rep3[order(SPO11tab$SPO11_1_oligos_Rep3,
                                                          decreasing = F)]
Naked_gDNA_R1 <- SPO11tab$Naked_gDNA_R1[order(SPO11tab$Naked_gDNA_R1,
                                              decreasing = F)]

SPO11list <- list(SPO11_1_oligos_Rep1,
                  SPO11_1_oligos_Rep2, 
                  SPO11_1_oligos_Rep3,
                  Naked_gDNA_R1) 

SPO11names <- c("SPO11-1-oligos Rep1",
                "SPO11-1-oligos Rep2",
                "SPO11-1-oligos Rep3",
                "Single-end gDNA")

SPO11colours <- c("dodgerblue2", "deepskyblue4", "lightskyblue", "grey50")

# H3
H3K4me3_ChIP <- H3tab$H3K4me3_ChIP[order(H3tab$H3K4me3_ChIP,
                                         decreasing = F)]
H3K9me2_ChIP <- H3tab$H3K9me2_ChIP[order(H3tab$H3K9me2_ChIP,
                                         decreasing = F)]
H3K27me3_ChIP_SRR1509478 <- H3tab$H3K27me3_ChIP_SRR1509478[order(H3tab$H3K27me3_ChIP_SRR1509478,
                                                                 decreasing = F)]
MNase <- H3tab$MNase[order(H3tab$MNase,
                           decreasing = F)]
H3K9me2_input <- H3tab$H3K9me2_input[order(H3tab$H3K9me2_input,
                                           decreasing = F)]
naked_gDNA <- H3tab$naked_gDNA[order(H3tab$naked_gDNA,
                                     decreasing = F)]

H3list <- list(H3K4me3_ChIP,
               H3K9me2_ChIP,
               H3K27me3_ChIP_SRR1509478,
               MNase,
               H3K9me2_input,
               naked_gDNA)

H3names <- c("H3K4me3 ChIP",
             "H3K9me2 ChIP",
             "H3K27me3 ChIP",
             "Nucleosomes (MNase-seq)",
             "Histone input",
             "Paired-end gDNA")

H3colours <- c("magenta", "green2", "blue", "darkcyan", "tan3", "grey50")

# Plot
pdf("./REC8_SPO11oligos_H3_fingerprints_R.pdf",
    height = 15, width = 5)
par(mfcol = c(3, 1),
    mar = c(5.2, 5.2, 1, 1),
    mgp = c(3, 1, 0))

# REC8
plot(x = percent_rank(REC8list[[1]]),
     y = cumsum(as.numeric(REC8list[[1]]))/
         cumsum(as.numeric(REC8list[[1]]))[length(cumsum(as.numeric(REC8list[[1]])))],
     type = "l",
     lwd = 3,
     col = REC8colours[1],
     ann = F,
     xaxt = "n",
     yaxt = "n")
sapply(2:length(REC8list), function(x) {
  lines(x = percent_rank(REC8list[[x]]),
        y = cumsum(as.numeric(REC8list[[x]]))/
            cumsum(as.numeric(REC8list[[x]]))[length(cumsum(as.numeric(REC8list[[x]])))],
        type = "l",
        lwd = 3,
        col = REC8colours[x])
})
lines(x = c(0, 1),
      y = c(0, 1),
      type = "l",
      lty = 5,
      lwd = 3)
abline(h = c(0.2),
       lwd = 3,
       lty = 3)
axis(side = 1, lwd.tick = 3, cex.axis = 1.2)
axis(side = 2, lwd.tick = 3, cex.axis = 1.2)
mtext(side = 1, line = 2.40, cex = 1,
      text = "Genomic bins ranked by coverage")
mtext(side = 2, line = 2.40, cex = 1,
      text = "Cumulative fraction of coverage\n relative to bin with highest coverage")
legend("topleft",
       legend = c(REC8names, "y = x"),
       col = c(REC8colours, "black"),
       text.col = c(REC8colours, "black"),
       lwd = 1.5,
       lty = c(rep(1, length(REC8list)), 5),
       cex = 1.2,
       bty = "n")
box(lwd = 3)

# SPO11-1-oligos
plot(x = percent_rank(SPO11list[[1]]),
     y = cumsum(as.numeric(SPO11list[[1]]))/
         cumsum(as.numeric(SPO11list[[1]]))[length(cumsum(as.numeric(SPO11list[[1]])))],
     type = "l",
     lwd = 3,
     col = SPO11colours[1],
     ann = F,
     xaxt = "n",
     yaxt = "n")
sapply(2:length(SPO11list), function(x) {
  lines(x = percent_rank(SPO11list[[x]]),
        y = cumsum(as.numeric(SPO11list[[x]]))/
            cumsum(as.numeric(SPO11list[[x]]))[length(cumsum(as.numeric(SPO11list[[x]])))],
        type = "l",
        lwd = 3,
        col = SPO11colours[x])
})
lines(x = c(0, 1),
      y = c(0, 1),
      type = "l",
      lty = 5,
      lwd = 3)
abline(h = c(0.2),
       lwd = 3,
       lty = 3)
axis(side = 1, lwd.tick = 3, cex.axis = 1.2)
axis(side = 2, lwd.tick = 3, cex.axis = 1.2)
mtext(side = 1, line = 2.40, cex = 1,
      text = "Genomic bins ranked by coverage")
mtext(side = 2, line = 2.40, cex = 1,
      text = "Cumulative fraction of coverage\n relative to bin with highest coverage")
legend("topleft",
       legend = c(SPO11names, "y = x"),
       col = c(SPO11colours, "black"),
       text.col = c(SPO11colours, "black"),
       lwd = 1.5,
       lty = c(rep(1, length(SPO11list)), 5),
       cex = 1.2,
       bty = "n")
box(lwd = 3)

# H3
plot(x = percent_rank(H3list[[1]]),
     y = cumsum(as.numeric(H3list[[1]]))/
         cumsum(as.numeric(H3list[[1]]))[length(cumsum(as.numeric(H3list[[1]])))],
     type = "l",
     lwd = 3,
     col = H3colours[1],
     ann = F,
     xaxt = "n",
     yaxt = "n")
sapply(2:length(H3list), function(x) {
  lines(x = percent_rank(H3list[[x]]),
        y = cumsum(as.numeric(H3list[[x]]))/
            cumsum(as.numeric(H3list[[x]]))[length(cumsum(as.numeric(H3list[[x]])))],
        type = "l",
        lwd = 3,
        col = H3colours[x])
})
lines(x = c(0, 1),
      y = c(0, 1),
      type = "l",
      lty = 5,
      lwd = 3)
abline(h = c(0.2),
       lwd = 3,
       lty = 3)
axis(side = 1, lwd.tick = 3, cex.axis = 1.2)
axis(side = 2, lwd.tick = 3, cex.axis = 1.2)
mtext(side = 1, line = 2.40, cex = 1,
      text = "Genomic bins ranked by coverage")
mtext(side = 2, line = 2.40, cex = 1,
      text = "Cumulative fraction of coverage\n relative to bin with highest coverage")
legend("topleft",
       legend = c(H3names, "y = x"),
       col = c(H3colours, "black"),
       text.col = c(H3colours, "black"),
       lwd = 1.5,
       lty = c(rep(1, length(H3list)), 5),
       cex = 1.2,
       bty = "n")
box(lwd = 3)

dev.off()
